#cloud-config
users:
  - default

package_update: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - runc

  # Enable ipv4 forwarding, required on CIS hardened machines
write_files:
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1

  - path: /etc/systemd/system/envoy.service
    content: |
      [Unit]
      Description=envoy
      Documentation=https://www.envoyproxy.io/docs

      [Service]
      Type=simple
      ExecStart=/usr/bin/envoy -c /app/envoy/front-envoy.yaml
      Restart=on-failure
      RestartSec=5

      [Install]
      WantedBy=multi-user.target

runcmd:
  - curl -sL 'https://getenvoy.io/gpg' | apt-key add -
  - apt-key fingerprint 6FF974DB | grep "5270 CEAC"
  - add-apt-repository "deb [arch=amd64] https://dl.bintray.com/tetrate/getenvoy-deb $(lsb_release -cs) stable"
  - apt update -y
  - apt install -y getenvoy-envoy

  - curl -sLSf https://github.com/containerd/containerd/releases/download/v1.5.2/containerd-1.5.2-linux-amd64.tar.gz > /tmp/containerd.tar.gz && tar -xvf /tmp/containerd.tar.gz -C /usr/local/bin/ --strip-components=1
  - curl -SLfs https://raw.githubusercontent.com/containerd/containerd/v1.5.2/containerd.service | tee /etc/systemd/system/containerd.service
  - systemctl daemon-reload && systemctl start containerd
  - systemctl enable containerd

  - mkdir -p /opt/cni/bin
  - curl -sSL https://github.com/containernetworking/plugins/releases/download/v0.9.1/cni-plugins-linux-amd64-v0.9.1.tgz | tar -xz -C /opt/cni/bin

  - mkdir -p /go/src/github.com/openfaas/
  - cd /go/src/github.com/openfaas/ && git clone --depth 1 --branch 0.11.4 https://github.com/openfaas/faasd
  - curl -fSLs "https://github.com/openfaas/faasd/releases/download/0.11.4/faasd" --output "/usr/local/bin/faasd" && chmod a+x "/usr/local/bin/faasd"
  - cd /go/src/github.com/openfaas/faasd/ && /usr/local/bin/faasd install
  - systemctl status -l containerd --no-pager
  - journalctl -u faasd-provider --no-pager
  - systemctl status -l faasd-provider --no-pager
  - systemctl status -l faasd --no-pager
  - curl -sSLf https://cli.openfaas.com | sh
  - sleep 60 && journalctl -u faasd --no-pager
  - cat /var/lib/faasd/secrets/basic-auth-password | /usr/local/bin/faas-cli login --password-stdin